# -*- coding: utf-8 -*-
"""AI-chatbot for college ERP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-oycp8VWGm8rRrjCIU-XUBr0S60N5Ba
"""

# Install required libraries
!pip install streamlit pyngrok pandas --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# # Store student data in session state
# if "students" not in st.session_state:
#     st.session_state.students = []
# 
# st.title("AI Chatbot for College ERP")
# 
# st.header("Enter Student Details")
# 
# # Input fields
# roll = st.text_input("Roll Number")
# name = st.text_input("Student Name")
# attendance = st.number_input("Attendance (%)", min_value=0, max_value=100)
# marks = st.number_input("Marks", min_value=0, max_value=100)
# exam_date = st.text_input("Exam Date (DD-MM-YYYY)")
# 
# # Add student button
# if st.button("Add Student"):
# 
#     if roll and name and exam_date:
# 
#         # Check duplicate roll numbers
#         roll_exists = any(student["Roll No"] == roll for student in st.session_state.students)
# 
#         if roll_exists:
#             st.error("Roll Number already exists")
# 
#         else:
#             st.session_state.students.append({
#                 "Roll No": roll,
#                 "Name": name,
#                 "Attendance (%)": attendance,
#                 "Marks": marks,
#                 "Exam Date": exam_date
#             })
# 
#             st.success("Student added successfully")
# 
#     else:
#         st.warning("Please fill all fields")
# 
# # Convert to DataFrame
# df = pd.DataFrame(st.session_state.students)
# 
# # Display student table
# if not df.empty:
#     st.subheader("Student Data")
#     st.dataframe(df)
# 
# # Chatbot Section
# st.subheader("Chatbot")
# 
# roll_no = st.text_input("Enter Your Roll Number")
# query = st.text_input("Ask your question (attendance / marks / exam)")
# 
# def chatbot_response(query, roll_no):
# 
#     student = df[df["Roll No"].astype(str) == str(roll_no)]
# 
#     if student.empty:
#         return "Student not found"
# 
#     name = student["Name"].values[0]
#     attendance = int(student["Attendance (%)"].values[0])
#     marks = int(student["Marks"].values[0])
#     exam = student["Exam Date"].values[0]
# 
#     query = query.lower()
# 
#     if "attendance" in query:
# 
#         if attendance < 75:
#             return f"{name}, your attendance is {attendance}%. Please improve it. Minimum required attendance is 75%."
# 
#         else:
#             return f"{name}, your attendance is {attendance}%."
# 
#     elif "marks" in query:
# 
#         if marks < 35:
#             return f"{name}, your marks are {marks}. You need to improve your marks."
# 
#         else:
#             return f"{name}, your marks are {marks}."
# 
#     elif "exam" in query:
#         return f"{name}, your exam date is {exam}."
# 
#     else:
#         return "I can answer only about attendance, marks, and exam dates."
# 
# # Chatbot button
# if st.button("Get Answer"):
# 
#     if roll_no == "" or query == "":
#         st.warning("Please enter Roll Number and Question")
# 
#     else:
#         response = chatbot_response(query, roll_no)
# 
#         if "improve" in response or "not found" in response:
#             st.error(response)
#         else:
#             st.success(response)

from pyngrok import ngrok

# 🔑 Paste your FULL authtoken here
ngrok.set_auth_token("3AHurhClNyhPwNCU2ByZVc3H3aV_4CjP7ugDGaFwUjYeXGu4H")

!streamlit run app.py &>/dev/null &

public_url = ngrok.connect(8501)

print("Click this link to open your ERP Chatbot:")
print(public_url)